spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3307/demo_app
    username: root
    password: pass1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    timeout: 60000

  cache:
    type: redis
    redis:
      time-to-live: 60000

jwt:
  key: replaceYourSecretKeyHere
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.demo: INFO
