services:
  db:
    container_name: demo-db
    image: mysql:8.0
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: demo_app
      MYSQL_ROOT_HOST: '%'
  redis:
    image: redis:7.0.10-alpine
    container_name: demo-redis
    entrypoint: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"